name = input("Enter your name: ")
address1 = input("Enter your address line 1: ")
address2 = input("Enter your address line 2: ")
address3 = input("Enter your address line 3: ")
city = input("Enter your city: ")
state = input("Enter your state name: ")
pin = input("Enter your pincode: ")

print(name)
print("Address: ")
print(address1, ", ")
print(address2, ', ')
print(address3, ", ")
print(city, "- ", pin)
print(state)
